# ===========================================
# Smart SIEM Agent Configuration
# ===========================================

agent:
  name: "Smart-SIEM-Agent"
  version: "1.0.0"
  environment: "development"

backend:
  url: "http://10.237.69.157:8000/api/logs/ingest"
  timeout: 10
  retry_interval: 5

logs:

  files:
    - "/var/log/syslog"
    - "/var/log/auth.log"
    #- "/var/log/siem/dmz/*.log"
    #- "/var/log/siem/lan/*.log"
    #- "/var/log/siem/admin/*.log"

logging:

  level: "INFO"
  file: "logs/agent.log"

security:

  api_key: ""