name: CI Pipeline

on:
  push:
    branches: [ main, develop, "feature/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification que le pipeline se déclenche
        run: echo "Pipeline CI opérationnel - Smart SIEM"